import { BaseLLMProvider } from './base-provider';
import { LLMRequest, LLMResponse } from './types';

export class AnthropicProvider extends BaseLLMProvider {
  private baseUrl = 'https://api.anthropic.com/v1';

  async generateContent(request: LLMRequest): Promise<LLMResponse> {
    this.validateRequest(request);

    try {
      const response = await fetch(`${this.baseUrl}/messages`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-api-key': this.apiKey,
          'anthropic-version': '2023-06-01',
        },
        body: JSON.stringify({
          model: request.model || this.model,
          max_tokens: request.maxTokens || this.maxTokens,
          temperature: request.temperature || this.temperature,
          messages: [
            {
              role: 'user',
              content: request.prompt,
            },
          ],
        }),
      });

      if (!response.ok) {
        const error = await response.json();
        throw new Error(`Anthropic API error: ${error.error?.message || 'Unknown error'}`);
      }

      const data = await response.json();
      const content = data.content[0]?.text;

      if (!content) {
        throw new Error('No content generated by Anthropic');
      }

      return this.formatResponse(content, data.usage);
    } catch (error) {
      console.error('Anthropic API error:', error);
      throw new Error(`Failed to generate content: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }
}
